### ISSUE TITLE
rename occurences of f! to f

### ISSUE THREAD

**Issue by hexaeder** [PIK-ICoNe/NetworkDynamics.jl#105]
For a future breaking release I'd like to change all occurrences of `f!` to `f`. I know all of our functions are mutating but it breaks the two most common Julia styles, [BlueStyle](https://github.com/invenia/BlueStyle) and [YASStyle](https://github.com/jrevels/YASGuide).
Those guides forbid spaces around `=` in keyword arguments. But `ODEVertex(f! = foo, ...)` gets parsed totally different from `ODEVertex(f!=foo, ...)` (since the latter is not-equal).

**Comment by lindnemi** [comment]
Sure, go for it :)
