### ISSUE TITLE
Integration Test with PowerDynamics

### ISSUE THREAD

**Issue by FHell** [PIK-ICoNe/NetworkDynamics.jl#11]
PowerDynamics depends on the proper functioning of this package. We need to make sure that we don't break PowerDynamics:

I don't know right now how to create test like that (make another package use the currently being tested package...)

**Comment by SabineAuer** [comment]
@janlisse? :)

**Comment by janlisse** [comment]
One way to implement this:
If you setup a Travis CI job for your project, you could add another project which could be triggered by Travis API: https://docs.travis-ci.com/user/triggering-builds/
You would pass the NetworkDynamics branch that you want to test against as an environment variable for the triggered build. In the integration test project you can then load the passed NetworkDynamics branch from a git url, PowerDynamics latest release or master from git and run whatever test code makes sense.

**Comment by lindnemi** [comment]
https://github.com/abelsiqueira/Breakage

https://discourse.julialang.org/t/ann-github-action-workflow-to-test-if-your-pr-breaks-another-package-reverse-dependency-integration-testing/57635
