### ISSUE TITLE
Graphs.jl compatibility with NetworkDynamics,jl

### ISSUE THREAD

**Issue by venkatachalapathy** [PIK-ICoNe/NetworkDynamics.jl#113]
Is the new package Graph.jl compatible with NetworkDynamics.jl? If yes, are there any known issues?

**Comment by hexaeder** [comment]
NetworkDynamics 0.6 was using LightGraphs, we did the switch to Graphs in 0.7. There are no problems since Graphs.jl and LightGraphs.jl are the exact same come, it was just a namechange.
