### ISSUE TITLE
Is it possible to change graphs and their adjacency matrices during problem solving?

### ISSUE THREAD

**Issue by CCTV173** [PIK-ICoNe/NetworkDynamics.jl#124]

**Comment by CCTV173** [comment]
![VHJ5NM34NYLIGX VO{`W M](https://user-images.githubusercontent.com/87682150/213127114-3ee6615c-5c58-4cc0-b82e-c2887aac76fe.png)

**Comment by CCTV173** [comment]
I‘m wondering whether  NetworkDynamics.jl can change the adjacency matrix of graph in the process of solving ODEproblem? Is it possible to use CallbackSet ?

**Comment by lindnemi** [comment]
It's not possible to directly change the adjacency matrix. However you can introduce an edge weight and use a callback to set it to 0 during integration. Take a look at [the cascading failure example](https://github.com/PIK-ICoNe/NetworkDynamics.jl/blob/main/examples/cascading_failure.jl).

**Comment by CCTV173** [comment]
Thanks！

Micha ***@***.***> 于2023年1月18日周三 17:14写道：
