### ISSUE TITLE
Modeling of Migration Flow

### ISSUE THREAD

**Issue by dave7895** [PIK-ICoNe/NetworkDynamics.jl#134]
Hey, this has been a very useful package so far, thanks!
I am facing a problem when trying to model to model a problem where both the incoming and the outgoing edges are relevant for modeling.
The problem is that my weight matrix is not symmetric and the value of my node depends on the outgoing coupling and the value of the target node. 
`ẋ_i = α * y + W_ij * x_i + W_ji * x_j` with the last part being summed over all j values.
Is the only way to go then to use fiducial coupling with the parameter being (W_ij, W_ji) for each edge (i -> j)?

**Comment by hexaeder** [comment]
I think your correct. It cannot be done with `symmetric` or `antisymmetric` coupling. You could alternatively use `directed` where you create two edges on a digraph for each link, one going 
- from `i -> j` with `e = W_ij * x_i` and
- from `j -> i` with `e = W_ji * x_j`

Maybe parameter wise that's actually simpler because your parameter array for the edges becomes something like
```
map edges(g) do e
    W[e.src, e.dst]
end
```

**Comment by dave7895** [comment]
I think I may have confused some things. The edge function is actually symmetric because I forgot a minus sign if we have network of just nodes 1 and 2 then `dx_1 = W_12 * x_1 + W_21 * x_2` and `dx_2 = W_21 * x_2 + W_12 * x_1`.
The problem is not that the edge has a different coupling in the different directions but that the coupling strengths for source and destination vertex are different.
```julia
function edgefun!(e, v_s, v_d, p, t)
    W_ij, W_ji = p
    e = v_s * W_ij + v_d * W_ji
end
```
should work if `edgefun`only gets called with `i ≙ v_s` and `j ≙ v_d` and never with `j ≙ v_s` and `i ≙ v_d`, right?
If that is not the case, directed or fiducial would definitely be necessary.

**Comment by hexaeder** [comment]
I think `directed` is the way to go here. If you have a `SimpleDiGraph`, you can specify the edge direction explicitly, i.e. 1:1=>2 is a different object from `e2:2=>1`. The function for `e1` will be only called with `v1` as source and `v2` as destination, the `e2` the other way around.

**Comment by dave7895** [comment]
Yeah, this works perfectly now, thank you.
