### ISSUE TITLE
MethodError for empty edge list

### ISSUE THREAD

**Issue by antonplietzsch** [PIK-ICoNe/NetworkDynamics.jl#88]
In the last CI run for PowerDynamics we got an error in two specific tests. Both tests are designed in a way, that the edge list is actually empty. We can easily circumvent this problem by adding lines to the testcase and everything runs smooth. But I assume that something changed in the last release of NetworkDynamics, such that you cannot hand over an empty edge list anymore. Here is a minimal example:

```julia
using NetworkDynamics, OrdinaryDiffEq, LightGraphs

N = 4
g = SimpleGraph(N)

function kuramoto_vertex!(dθ, θ, edges, ω, t)
    dθ[1] = ω
    sum_coupling!(dθ, edges)
end

edge_array = []

vertex! = ODEVertex(f! = kuramoto_vertex!, dim = 1, sym=[:θ])
nd! = network_dynamics(vertex!, edge_array, g)
```
This give the following error when executing the `network_dynamics()` function:
```julia
ERROR: LoadError: MethodError: no method matching zero(::Type{Any})
```

I'm not sure if this is case we actually want to cover, but apparently it worked before.

**Comment by hexaeder** [comment]
for the PD tests, this problem occures first when going from [v0.5.2 to v0.5.3](https://github.com/PIK-ICoNe/NetworkDynamics.jl/compare/v0.5.2...v0.5.3)

**Comment by lindnemi** [comment]
I'm wondering why that doesn't get caught here: https://github.com/PIK-ICoNe/NetworkDynamics.jl/blob/59a2f9a73c4a3b179686dcee629531ecb4d5e563/src/NetworkDynamics.jl#L220
