### ISSUE TITLE
slow CI on 1.5

### ISSUE THREAD

**Issue by hexaeder** [PIK-ICoNe/NetworkDynamics.jl#93]
CI is much slower on Julia 1.5 than 1.6. It seems like the implicit solvers take forever, for example this line
https://github.com/PIK-ICoNe/NetworkDynamics.jl/blob/6abb721305d56e1193326c34b6b30db07425fd42/test/diffusion_test.jl#L140

**Comment by hexaeder** [comment]
seems to be a weird initialisation/precompilation thing. The first run takes forever (~10 min?) to just create 14 timesteps. After that it is less than a second. I've tried to manually pass a very short time span for initialisation but it still takes a long time.

**Comment by lindnemi** [comment]
hmmm then it might be a problem of OrdinaryDiffEq.jl on julia 1.5?

**Comment by lindnemi** [comment]
whatever, it was, the CI is now on 1.6 and 1.7 only
